package com.java.ds.StreamInJava.Stream25;

import java.util.stream.Stream;

/*
 What is stream in java  : 
        Stream can be the thought of as a stream of message flowing through the pipeline is called as stream .
        A Stream may be generated by reading the message out of a source like spout or by transforming other stream.

 */


public class WhatIsStream {
    public static void main(String[] args) {
        String logs = " This is the ERROR Message of the given Code";
       System.out.println(logs);

        
    }
    
}
